/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package manifests answers a question none of the other tests in this
// repo can: does dist/install.yaml - the file curriculum/11-packaging.md
// tells a reader to `kubectl apply -f`, generated by `make
// build-installer` - actually get accepted by a real Kubernetes API
// server? `make manifests` proves controller-gen produces valid YAML.
// `helm lint`/`helm template` prove the chart renders. Neither proves the
// API server will accept what comes out - a bad RBAC verb, a malformed
// selector, or a field the schema rejects would slip through both.
//
// This test applies the real, generated dist/install.yaml (not a
// hand-copied excerpt) against envtest's real kube-apiserver and asserts
// every object is accepted. It skips cert-manager.io objects (Issuer,
// Certificate) - envtest only has the built-in Kubernetes API types
// installed, not cert-manager's CRDs, and installing them just to
// validate three objects this repo doesn't own the schema of would be
// testing cert-manager, not this operator. See curriculum/11-packaging.md.
package manifests

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"testing"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/yaml"
	"k8s.io/client-go/discovery"
	"k8s.io/client-go/discovery/cached/memory"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/restmapper"
	"sigs.k8s.io/controller-runtime/pkg/envtest"
)

func TestInstallManifestIsAcceptedByAPIServer(t *testing.T) {
	testEnv := &envtest.Environment{}
	cfg, err := testEnv.Start()
	if err != nil {
		t.Fatalf("starting envtest: %v", err)
	}
	t.Cleanup(func() {
		if err := testEnv.Stop(); err != nil {
			t.Errorf("stopping envtest: %v", err)
		}
	})

	objs := loadInstallManifest(t)
	if len(objs) == 0 {
		t.Fatal("dist/install.yaml parsed to zero objects - is `make build-installer` up to date?")
	}

	dyn, err := dynamic.NewForConfig(cfg)
	if err != nil {
		t.Fatalf("building dynamic client: %v", err)
	}
	mapper := restMapper(t, cfg)

	applied := 0
	for _, obj := range objs {
		gvk := obj.GroupVersionKind()
		if gvk.Group == "cert-manager.io" {
			continue // see package doc
		}

		mapping, err := mapper.RESTMapping(gvk.GroupKind(), gvk.Version)
		if err != nil {
			t.Errorf("%s %s/%s: no REST mapping (unknown kind to this API server): %v",
				gvk.Kind, obj.GetNamespace(), obj.GetName(), err)
			continue
		}

		ns := obj.GetNamespace()
		var rc dynamic.ResourceInterface = dyn.Resource(mapping.Resource)
		if ns != "" {
			rc = dyn.Resource(mapping.Resource).Namespace(ns)
		}

		if ns != "" {
			ensureNamespace(t, dyn, mapper, ns)
		}

		if _, err := rc.Create(context.Background(), &obj, metav1.CreateOptions{}); err != nil {
			t.Errorf("apiserver rejected %s %s/%s: %v", gvk.Kind, ns, obj.GetName(), err)
			continue
		}
		applied++
	}

	t.Logf("applied %d/%d objects from dist/install.yaml (cert-manager.io objects skipped)", applied, len(objs))
}

func loadInstallManifest(t *testing.T) []unstructured.Unstructured {
	t.Helper()
	path := filepath.Join("..", "..", "dist", "install.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v (run `make build-installer` first)", path, err)
	}

	var objs []unstructured.Unstructured
	decoder := yaml.NewYAMLOrJSONDecoder(bytes.NewReader(data), 4096)
	for {
		var u unstructured.Unstructured
		if err := decoder.Decode(&u); err != nil {
			break
		}
		if len(u.Object) == 0 {
			continue
		}
		objs = append(objs, u)
	}
	return objs
}

func restMapper(t *testing.T, cfg *rest.Config) *restmapper.DeferredDiscoveryRESTMapper {
	t.Helper()
	dc, err := discovery.NewDiscoveryClientForConfig(cfg)
	if err != nil {
		t.Fatalf("building discovery client: %v", err)
	}
	return restmapper.NewDeferredDiscoveryRESTMapper(memory.NewMemCacheClient(dc))
}

func ensureNamespace(t *testing.T, dyn dynamic.Interface, _ *restmapper.DeferredDiscoveryRESTMapper, name string) {
	t.Helper()
	nsGVR := schema.GroupVersionResource{Version: "v1", Resource: "namespaces"}
	ns := &unstructured.Unstructured{Object: map[string]any{
		"apiVersion": "v1",
		"kind":       "Namespace",
		"metadata":   map[string]any{"name": name},
	}}
	_, _ = dyn.Resource(nsGVR).Create(context.Background(), ns, metav1.CreateOptions{})
}
